Propagate message send errors to the caller
This propagates message serialization and send errors up to the caller so that
we don't see cryptic `TimeoutError: None` exceptions instead.

Before:

```
    [..]
  File "[..]/tchannel-python/tchannel/tornado/peer.py", line 440, in _send
    response = yield response_future
  File "[..]/tchannel-python/env/lib/python2.7/site-packages/tornado-4.4.2-py2.7-macosx-10.11-x86_64.egg/tornado/gen.py", line 1015, in run
    value = future.result()
  File "[..]/tchannel-python/env/lib/python2.7/site-packages/tornado-4.4.2-py2.7-macosx-10.11-x86_64.egg/tornado/concurrent.py", line 237, in result
    raise_exc_info(self._exc_info)
  File "<string>", line 3, in raise_exc_info
tchannel.errors.TimeoutError: None``
```

After:

```
Traceback (most recent call last):
    [..]
  File "[..]/tchannel-python/tchannel/rw.py", line 574, in length_no_args
    size += rw.length(value)
  File "[..]/tchannel-python/tchannel/rw.py", line 617, in length
    size += self._pair.length(pair)
  File "[..]/tchannel-python/tchannel/rw.py", line 478, in length
    size += link.length(item)
  File "[..]/tchannel-python/tchannel/rw.py", line 446, in length
    s = s.encode('utf-8')
AttributeError: 'NoneType' object has no attribute 'encode'
```